import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { convertHtmlToJson } from '@/lib/gemini'; // I will use this later

export const dynamic = 'force-dynamic';

async function fetchHtml(url: string) {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      console.error(`Failed to fetch ${url}: ${response.statusText}`);
      return null;
    }
    return await response.text();
  } catch (error) {
    console.error(`Error fetching ${url}:`, error);
    return null;
  }
}

function extractLinks(jsonData: any): string[] {
    const links: string[] = [];
    if (typeof jsonData !== 'object' || jsonData === null) {
        return links;
    }

    for (const key in jsonData) {
        if (Array.isArray(jsonData[key])) {
            for (const item of jsonData[key]) {
                if (typeof item === 'object' && item !== null && typeof item.link === 'string') {
                    links.push(item.link);
                }
            }
        }
    }
    return links;
}


export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { jsonContent } = body;

    if (!jsonContent) {
      return NextResponse.json({ error: 'jsonContent is required' }, { status: 400 });
    }

    const parsedJson = JSON.parse(jsonContent);
    const links = extractLinks(parsedJson);

    if (links.length === 0) {
        return NextResponse.json({ message: 'No links found to process' });
    }

    const dirPath = path.join(process.cwd(), 'json', 'details', 'jobDetailPage-json');
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    // I will add the processing logic here in the next steps.
    // For now, just returning the links.
    // In the final implementation, I will loop through links, fetch html,
    // call gemini, and save the json.

    for (const link of links) {
        const html = await fetchHtml(link);
        if (html) {
            // This is a placeholder for the detail page prompt
            const detailPrompt = `Convert the following HTML of a job/result/admit card detail page into a structured JSON. Extract all key information like title, post date, description, application fees, important dates, eligibility, vacancy details, and any other relevant information. The JSON should be well-structured. Output only the JSON.`;
            
            try {
                // In a real scenario, I would replace the existing convertHtmlToJson or create a new one with the detailPrompt
                // For now, let's simulate the JSON generation.
                // const generatedJson = await convertHtmlToJson(html);
                
                const urlParts = link.split('/').filter(part => part);
                const fileName = `${urlParts[urlParts.length - 1] || 'details'}_${Date.now()}.json`;
                const filePath = path.join(dirPath, fileName);

                // Creating a dummy json for now.
                const dummyJson = {
                    "source_url": link,
                    "title": "Dummy Title for " + link,
                    "content": "This is dummy content. In the real implementation, this would be the JSON generated by Gemini."
                };

                fs.writeFileSync(filePath, JSON.stringify(dummyJson, null, 2));

            } catch (error) {
                console.error(`Failed to process link ${link}:`, error);
            }
        }
    }


    return NextResponse.json({ message: 'Started processing links. Check the json/details/jobDetailPage-json folder.' });

  } catch (error) {
    console.error('Error processing request:', error);
    return NextResponse.json({ error: 'Failed to process request' }, { status: 500 });
  }
}